import { Prisma, PrismaClient } from '@prisma/client';
import { prisma } from '../config/database';
import { IProductRepository, ProductFilter } from './interfaces';
import { ProductRecord } from '../types/domain';

const DEFAULT_PAGE = 1;
const DEFAULT_LIMIT = 20;
const MAX_LIMIT = 100;

export class ProductRepository implements IProductRepository {
  constructor(private readonly client: PrismaClient = prisma) {}

  async findMany(filter: ProductFilter): Promise<{ items: ProductRecord[]; total: number }> {
    const page = Math.max(filter.page ?? DEFAULT_PAGE, 1);
    const limit = Math.min(Math.max(filter.limit ?? DEFAULT_LIMIT, 1), MAX_LIMIT);

    // NOTE: `Prisma.ProductWhereInput` is a type generated by `prisma
    const where: Prisma.ProductWhereInput = {
      isActive: true,
      ...(filter.categoryId ? { categoryId: filter.categoryId } : {}),
      ...(filter.search
        ? { name: { contains: filter.search, mode: 'insensitive' as const } }
        : {})
    };

    const [rows, total] = await Promise.all([
      this.client.product.findMany({
        where,
        skip: (page - 1) * limit,
        take: limit,
        orderBy: { createdAt: 'desc' }
      }),
      this.client.product.count({ where })
    ]);

    return { items: rows.map(this.toDomain), total };
  }

  async findById(id: string): Promise<ProductRecord | null> {
    const row = await this.client.product.findUnique({ where: { id } });
    return row ? this.toDomain(row) : null;
  }

  async create(input: Omit<ProductRecord, 'id' | 'createdAt' | 'isActive'>): Promise<ProductRecord> {
    const row = await this.client.product.create({
      data: {
        name: input.name,
        description: input.description,
        price: input.price,
        stockQuantity: input.stockQuantity,
        categoryId: input.categoryId
      }
    });
    return this.toDomain(row);
  }

  async update(id: string, data: Partial<Omit<ProductRecord, 'id' | 'createdAt'>>): Promise<ProductRecord> {
    const row = await this.client.product.update({
      where: { id },
      data: {
        ...(data.name !== undefined ? { name: data.name } : {}),
        ...(data.description !== undefined ? { description: data.description } : {}),
        ...(data.price !== undefined ? { price: data.price } : {}),
        ...(data.stockQuantity !== undefined ? { stockQuantity: data.stockQuantity } : {}),
        ...(data.categoryId !== undefined ? { categoryId: data.categoryId } : {}),
        ...(data.isActive !== undefined ? { isActive: data.isActive } : {})
      }
    });
    return this.toDomain(row);
  }

  async deactivate(id: string): Promise<ProductRecord> {
    const row = await this.client.product.update({ where: { id }, data: { isActive: false } });
    return this.toDomain(row);
  }

  async decrementStock(productId: string, quantity: number): Promise<void> {
    // Uses an atomic `decrement` so concurrent checkouts cannot race each
    // other into negative stock between a read and a write.
    await this.client.product.update({
      where: { id: productId },
      data: { stockQuantity: { decrement: quantity } }
    });
  }

  private toDomain(row: any): ProductRecord {
    return {
      id: row.id,
      name: row.name,
      description: row.description,
      price: Number(row.price),
      stockQuantity: row.stockQuantity,
      categoryId: row.categoryId,
      isActive: row.isActive,
      createdAt: row.createdAt
    };
  }
}
